SET NAMES utf8mb4;

DELETE FROM `compte` WHERE `no_compte` = '2';

INSERT INTO `compte` (`no_compte`, `nom`, `age`, `email1`, `motdepasse`, `actif`) VALUES
(2, 'Démonstration', 1990, 'demo@moncycle.app', '$2y$10$hTn9Xjg4wk/ovWEY8BWXau.Y1ODRoX03c2zlp6Rnmib1yUcVpp0sC', 1);

INSERT INTO `observation` (`no_observation`, `no_compte`, `date_obs`, `gommette`, `sensation`, `jour_sommet`, `union_sex`, `premier_jour`, `commentaire`, `dernier_modif`) VALUES
(1,	2,	CURDATE() + INTERVAL -73 DAY,	'.',	NULL,	NULL,	NULL,	1,	'',	NULL),
(2,	2,	CURDATE() + INTERVAL -72 DAY,	'.',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(3,	2,	CURDATE() + INTERVAL -71 DAY,	'.',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(4,	2,	CURDATE() + INTERVAL -70 DAY,	'.',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(5,	2,	CURDATE() + INTERVAL -69 DAY,	'.',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(6,	2,	CURDATE() + INTERVAL -68 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'jour non observé (oubli)',	NULL),
(7,	2,	CURDATE() + INTERVAL -67 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(8,	2,	CURDATE() + INTERVAL -66 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(9,	2,	CURDATE() + INTERVAL -65 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(10,	2,	CURDATE() + INTERVAL -64 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(11,	2,	CURDATE() + INTERVAL -63 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(12,	2,	CURDATE() + INTERVAL -62 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(13,	2,	CURDATE() + INTERVAL -61 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(14,	2,	CURDATE() + INTERVAL -60 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(15,	2,	CURDATE() + INTERVAL -59 DAY,	'I',	NULL,	NULL,	1,	NULL,	'',	NULL),
(16,	2,	CURDATE() + INTERVAL -58 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(17,	2,	CURDATE() + INTERVAL -57 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(18,	2,	CURDATE() + INTERVAL -56 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(19,	2,	CURDATE() + INTERVAL -55 DAY,	':)',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(20,	2,	CURDATE() + INTERVAL -54 DAY,	':)',	'humide, elastique, blanc',	NULL,	NULL,	NULL,	'',	NULL),
(21,	2,	CURDATE() + INTERVAL -53 DAY,	':)',	'collant, Jaune',	NULL,	1,	NULL,	'',	NULL),
(22,	2,	CURDATE() + INTERVAL -52 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(23,	2,	CURDATE() + INTERVAL -51 DAY,	':)',	'humide, elastique',	NULL,	NULL,	NULL,	'',	NULL),
(24,	2,	CURDATE() + INTERVAL -50 DAY,	':)',	'humide, elastique, transparent',	NULL,	NULL,	NULL,	'',	NULL),
(25,	2,	CURDATE() + INTERVAL -49 DAY,	':)',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(26,	2,	CURDATE() + INTERVAL -48 DAY,	':)',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(27,	2,	CURDATE() + INTERVAL -47 DAY,	':)',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(28,	2,	CURDATE() + INTERVAL -46 DAY,	':)',	NULL,	1,	NULL,	NULL,	'',	NULL),
(29,	2,	CURDATE() + INTERVAL -45 DAY,	':)',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(30,	2,	CURDATE() + INTERVAL -44 DAY,	'I',	'sec',	NULL,	NULL,	NULL,	'',	NULL),
(31,	2,	CURDATE() + INTERVAL -43 DAY,	'I',	'sec',	NULL,	NULL,	NULL,	'',	NULL),
(32,	2,	CURDATE() + INTERVAL -42 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(33,	2,	CURDATE() + INTERVAL -41 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(34,	2,	CURDATE() + INTERVAL -40 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(35,	2,	CURDATE() + INTERVAL -39 DAY,	'I',	NULL,	NULL,	1,	NULL,	'',	NULL),
(36,	2,	CURDATE() + INTERVAL -38 DAY,	'?',	NULL,	NULL,	1,	NULL,	'',	NULL),
(37,	2,	CURDATE() + INTERVAL -37 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(38,	2,	CURDATE() + INTERVAL -36 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(39,	2,	CURDATE() + INTERVAL -35 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(40,	2,	CURDATE() + INTERVAL -34 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(41,	2,	CURDATE() + INTERVAL -33 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(42,	2,	CURDATE() + INTERVAL -32 DAY,	'=',	'humide, jaune, pâteux, collant',	NULL,	NULL,	NULL,	'',	NULL),
(43,	2,	CURDATE() + INTERVAL -31 DAY,	'=',	'humide',	NULL,	NULL,	NULL,	'Idem veille',	NULL),
(45,	2,	CURDATE() + INTERVAL -30 DAY,	'.',	NULL,	NULL,	NULL,	1,	'',	NULL),
(46,	2,	CURDATE() + INTERVAL -29 DAY,	'.',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(47,	2,	CURDATE() + INTERVAL -28 DAY,	'.',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(48,	2,	CURDATE() + INTERVAL -27 DAY,	'.',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(49,	2,	CURDATE() + INTERVAL -26 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'Avec traces rouges',	NULL),
(50,	2,	CURDATE() + INTERVAL -25 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'Avec traces rouges',	NULL),
(51,	2,	CURDATE() + INTERVAL -24 DAY,	'I',	'sec',	NULL,	NULL,	NULL,	'Rien ',	NULL),
(52,	2,	CURDATE() + INTERVAL -23 DAY,	':)',	'humide',	NULL,	NULL,	NULL,	'',	NULL),
(53,	2,	CURDATE() + INTERVAL -22 DAY,	':)',	'humide',	NULL,	NULL,	NULL,	'',	NULL),
(54,	2,	CURDATE() + INTERVAL -21 DAY,	':)',	'humide',	NULL,	NULL,	NULL,	'',	NULL),
(55,	2,	CURDATE() + INTERVAL -20 DAY,	':)',	'humide',	NULL,	NULL,	NULL,	'',	NULL),
(56,	2,	CURDATE() + INTERVAL -19 DAY,	':)',	'humide',	NULL,	NULL,	NULL,	'???? Je suis perdu à moitié sec',	NULL),
(57,	2,	CURDATE() + INTERVAL -18 DAY,	'I',	'sec',	NULL,	NULL,	NULL,	'',	NULL),
(58,	2,	CURDATE() + INTERVAL -17 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(59,	2,	CURDATE() + INTERVAL -16 DAY,	':)',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(60,	2,	CURDATE() + INTERVAL -15 DAY,	':)',	NULL,	1,	NULL,	NULL,	'',	NULL),
(61,	2,	CURDATE() + INTERVAL -14 DAY,	':)',	NULL,	NULL,	NULL,	NULL,	'Un peu moins ',	NULL),
(62,	2,	CURDATE() + INTERVAL -13 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(63,	2,	CURDATE() + INTERVAL -12 DAY,	'I',	'sec',	NULL,	NULL,	NULL,	'',	NULL),
(64,	2,	CURDATE() + INTERVAL -11 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(65,	2,	CURDATE() + INTERVAL -10 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(66,	2,	CURDATE() + INTERVAL -9 DAY,	'I',	NULL,	NULL,	1,	NULL,	'',	NULL),
(67,	2,	CURDATE() + INTERVAL -8 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(68,	2,	CURDATE() + INTERVAL -7 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(69,	2,	CURDATE() + INTERVAL -6 DAY,	'I',	NULL,	NULL,	1,	NULL,	'',	NULL),
(70,	2,	CURDATE() + INTERVAL -5 DAY,	'?',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(71,	2,	CURDATE() + INTERVAL -4 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(72,	2,	CURDATE() + INTERVAL -3 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(73,	2,	CURDATE() + INTERVAL -2 DAY,	'I',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(74,	2,	CURDATE() + INTERVAL -1 DAY,	'',	NULL,	NULL,	NULL,	NULL,	'',	NULL),
(75,	2,	CURDATE(),	'',	NULL,	NULL,	NULL,	NULL,	'',	NULL);
