SET NAMES utf8mb4;

DELETE FROM `compte` WHERE `no_compte` = '2';

INSERT INTO `compte` (`no_compte`, `nom`, `age`, `email1`, `motdepasse`, `actif`) VALUES
(2, 'Démonstration', 1990, 'demo@moncycle.app', '$2y$10$hTn9Xjg4wk/ovWEY8BWXau.Y1ODRoX03c2zlp6Rnmib1yUcVpp0sC', 1);

INSERT INTO `observation` (`no_observation`, `no_compte`, `date_obs`, `jenesaispas`, `gommette`, `sensation`, `temperature`, `jour_sommet`, `union_sex`, `premier_jour`, `commentaire`) VALUES
(1,	2,	CURDATE() + INTERVAL - (75-1) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	1,	''),
(2,	2,	CURDATE() + INTERVAL - (75-2) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(3,	2,	CURDATE() + INTERVAL - (75-3) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(4,	2,	CURDATE() + INTERVAL - (75-4) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(5,	2,	CURDATE() + INTERVAL - (75-5) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(6,	2,	CURDATE() + INTERVAL - (75-6) DAY,	1,	'',	NULL,	NULL,	NULL,	NULL,	NULL,	'jour non observé (oubli)'),
(7,	2,	CURDATE() + INTERVAL - (75-7) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(8,	2,	CURDATE() + INTERVAL - (75-8) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(9,	2,	CURDATE() + INTERVAL - (75-9) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(10,	2,	CURDATE() + INTERVAL - (75-10) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(11,	2,	CURDATE() + INTERVAL - (75-11) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(12,	2,	CURDATE() + INTERVAL - (75-12) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(13,	2,	CURDATE() + INTERVAL - (75-13) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(14,	2,	CURDATE() + INTERVAL - (75-14) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(15,	2,	CURDATE() + INTERVAL - (75-15) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	1,	NULL,	''),
(16,	2,	CURDATE() + INTERVAL - (75-16) DAY,	1,	'',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(17,	2,	CURDATE() + INTERVAL - (75-17) DAY,	1,	'',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(18,	2,	CURDATE() + INTERVAL - (75-18) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(19,	2,	CURDATE() + INTERVAL - (75-19) DAY,	NULL,	':)',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(20,	2,	CURDATE() + INTERVAL - (75-20) DAY,	NULL,	':)',	'humide, elastique, blanc',	NULL,	NULL,	NULL,	NULL,	''),
(21,	2,	CURDATE() + INTERVAL - (75-21) DAY,	NULL,	':)',	'collant, Jaune',	NULL,	NULL,	1,	NULL,	''),
(22,	2,	CURDATE() + INTERVAL - (75-22) DAY,	1,	'',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(23,	2,	CURDATE() + INTERVAL - (75-23) DAY,	NULL,	':)',	'humide, elastique',	NULL,	NULL,	NULL,	NULL,	''),
(24,	2,	CURDATE() + INTERVAL - (75-24) DAY,	NULL,	':)',	'humide, elastique, transparent',	NULL,	NULL,	NULL,	NULL,	''),
(25,	2,	CURDATE() + INTERVAL - (75-25) DAY,	NULL,	':)',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(26,	2,	CURDATE() + INTERVAL - (75-26) DAY,	NULL,	':)',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(27,	2,	CURDATE() + INTERVAL - (75-27) DAY,	NULL,	':)',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(28,	2,	CURDATE() + INTERVAL - (75-28) DAY,	NULL,	':)',	NULL,	NULL,	1,	NULL,	NULL,	''),
(29,	2,	CURDATE() + INTERVAL - (75-29) DAY,	NULL,	':)',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(30,	2,	CURDATE() + INTERVAL - (75-30) DAY,	NULL,	'I',	'sec',	NULL,	NULL,	NULL,	NULL,	''),
(31,	2,	CURDATE() + INTERVAL - (75-31) DAY,	NULL,	'I',	'sec',	NULL,	NULL,	NULL,	NULL,	''),
(32,	2,	CURDATE() + INTERVAL - (75-32) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(33,	2,	CURDATE() + INTERVAL - (75-33) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(34,	2,	CURDATE() + INTERVAL - (75-34) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(35,	2,	CURDATE() + INTERVAL - (75-35) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	1,	NULL,	''),
(36,	2,	CURDATE() + INTERVAL - (75-36) DAY,	1,	'',	NULL,	NULL,	NULL,	1,	NULL,	''),
(37,	2,	CURDATE() + INTERVAL - (75-37) DAY,	1,	'',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(38,	2,	CURDATE() + INTERVAL - (75-38) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(39,	2,	CURDATE() + INTERVAL - (75-39) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(40,	2,	CURDATE() + INTERVAL - (75-40) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(41,	2,	CURDATE() + INTERVAL - (75-41) DAY,	NULL,	'I',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(42,	2,	CURDATE() + INTERVAL - (75-42) DAY,	NULL,	'=',	'humide, jaune, pâteux, collant',	NULL,	NULL,	NULL,	NULL,	''),
(43,	2,	CURDATE() + INTERVAL - (75-43) DAY,	NULL,	'=',	'humide',	NULL,	NULL,	NULL,	NULL,	'Idem veille'),
(45,	2,	CURDATE() + INTERVAL - (75-45) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	1,	''),
(46,	2,	CURDATE() + INTERVAL - (75-46) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(47,	2,	CURDATE() + INTERVAL - (75-47) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(48,	2,	CURDATE() + INTERVAL - (75-48) DAY,	NULL,	'.',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(49,	2,	CURDATE() + INTERVAL - (75-49) DAY,	NULL,	'I',	NULL,	36.55,	NULL,	NULL,	NULL,	'Avec traces rouges'),
(50,	2,	CURDATE() + INTERVAL - (75-50) DAY,	NULL,	'I',	NULL,	36.50,	NULL,	NULL,	NULL,	'Avec traces rouges'),
(51,	2,	CURDATE() + INTERVAL - (75-51) DAY,	NULL,	'I',	'sec',	36.60,	NULL,	NULL,	NULL,	'Rien'),
(52,	2,	CURDATE() + INTERVAL - (75-52) DAY,	NULL,	'I',	NULL,	36.60,	NULL,	NULL,	NULL,	''),
(53,	2,	CURDATE() + INTERVAL - (75-53) DAY,	NULL,	'I',	NULL,	36.50,	NULL,	NULL,	NULL,	''),
(54,	2,	CURDATE() + INTERVAL - (75-54) DAY,	NULL,	'I',	'humide',	36.65,	NULL,	NULL,	NULL,	''),
(55,	2,	CURDATE() + INTERVAL - (75-55) DAY,	NULL,	'I',	'humide',	36.50,	NULL,	NULL,	NULL,	''),
(56,	2,	CURDATE() + INTERVAL - (75-56) DAY,	NULL,	':)',	'humide',	36.60,	NULL,	NULL,	NULL,	'Je suis pas sur'),
(57,	2,	CURDATE() + INTERVAL - (75-57) DAY,	NULL,	':)',	NULL,	36.65,	NULL,	1,	NULL,	''),
(58,	2,	CURDATE() + INTERVAL - (75-58) DAY,	NULL,	':)',	NULL,	36.60,	NULL,	NULL,	NULL,	''),
(59,	2,	CURDATE() + INTERVAL - (75-59) DAY,	NULL,	':)',	NULL,	36.55,	NULL,	NULL,	NULL,	''),
(60,	2,	CURDATE() + INTERVAL - (75-60) DAY,	NULL,	':)',	NULL,	36.65,	1,	NULL,	NULL,	''),
(61,	2,	CURDATE() + INTERVAL - (75-61) DAY,	NULL,	':)',	NULL,	37.05,	NULL,	NULL,	NULL,	'Un peu moins'),
(62,	2,	CURDATE() + INTERVAL - (75-62) DAY,	NULL,	'I',	NULL,	37.10,	NULL,	NULL,	NULL,	''),
(63,	2,	CURDATE() + INTERVAL - (75-63) DAY,	NULL,	'I',	'sec',	37.05,	NULL,	NULL,	NULL,	''),
(64,	2,	CURDATE() + INTERVAL - (75-64) DAY,	NULL,	'I',	NULL,	37.00,	NULL,	NULL,	NULL,	''),
(65,	2,	CURDATE() + INTERVAL - (75-65) DAY,	NULL,	'I',	NULL,	37.05,	NULL,	NULL,	NULL,	''),
(66,	2,	CURDATE() + INTERVAL - (75-66) DAY,	NULL,	'I',	NULL,	37.05,	NULL,	1,	NULL,	''),
(67,	2,	CURDATE() + INTERVAL - (75-67) DAY,	NULL,	'I',	NULL,	37.10,	NULL,	NULL,	NULL,	''),
(68,	2,	CURDATE() + INTERVAL - (75-68) DAY,	NULL,	'I',	NULL,	37.01,	NULL,	NULL,	NULL,	''),
(69,	2,	CURDATE() + INTERVAL - (75-69) DAY,	NULL,	'I',	NULL,	37.00,	NULL,	1,	NULL,	''),
(70,	2,	CURDATE() + INTERVAL - (75-70) DAY,	1,	'',	NULL,	NULL,	NULL,	NULL,	NULL,	''),
(71,	2,	CURDATE() + INTERVAL - (75-71) DAY,	NULL,	'I',	NULL,	37.10,	NULL,	NULL,	NULL,	''),
(72,	2,	CURDATE() + INTERVAL - (75-72) DAY,	NULL,	'I',	NULL,	37.05,	NULL,	NULL,	NULL,	''),
(73,	2,	CURDATE() + INTERVAL - (75-73) DAY,	NULL,	'I',	NULL,	37.00,	NULL,	NULL,	NULL,	''),
(74,	2,	CURDATE() + INTERVAL - (75-74) DAY,	NULL,	'I',	NULL,	37.05,	NULL,	NULL,	NULL,	'');

